### ISSUE TITLE
XMPP infinite login loop

### ISSUE THREAD

**Issue by timiimit** [timiimit/UT4UU-Public#2]
Version: 10.0b5-quickfix
Description: When XMPP fails to verify server's TLS certificate, infinite login loop starts.

**Comment by timiimit** [comment]
Fixed

**Comment by niobium93** [comment]
I updated to v10.1, but this still happens to me. Game just says `Checking your identity` while this keeps getting spammed in the terminal.
```
[2023.01.09-08.02.44:164][163]LogXmpp:Warning: Certificate verification failure: self signed certificate in certificate chain
[2023.01.09-08.02.44:164][163]LogXmpp:Warning: Issuer: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root G2
[2023.01.09-08.02.44:164][163]LogXmpp:Warning: Subject: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root G2
[2023.01.09-08.02.44:164][163]LogXmpp:Warning: Fingerprint SHA256: cb3ccbb76031e5e0138f8dd39a23f9de47ffc35e43c1144cea27d46a5ab1cb5f
[2023.01.09-08.02.44:164][163]LogXmpp:Warning: Fingerprint SHA1: df3c24f9bfd666761b268073fe06d1cc8d4f82a4
```

**Comment by timiimit** [comment]
Are you sure you are using v10.1? what version does it say when you use console command `uu info`? I assume you dont have auto-login enabled and are able to enter offline mode to use this command.
![image](https://user-images.githubusercontent.com/32331609/211318590-b9f1ebf8-219d-4c86-9c4c-8aa522ef9b02.png)

**Comment by niobium93** [comment]
![Screenshot_20230109_175954](https://user-images.githubusercontent.com/1523948/211352492-3562a8b4-9bde-488a-999f-9cbf481ce44c.png)

**Comment by timiimit** [comment]
I didn't properly test the new version on linux, but i tried it again now. I cannot seem to be able to replicate this issue. For further investigation consider making a new issue.

Make sure you have certificates installed in `/etc/ssl`. Use `update-ca-trust` command if they aren't there to configure this.
Some more info about similar issue: #6
